{
  "name": "Plasma Master",
  "author": "Plasma Theme Master",
  "themes": [
    {
      "name": "Plasma Master Light",
      "appearance": "light",
      "style": {
        "border": "{{ZED_SURFACE1}}",
        "border.variant": "{{ZED_SURFACE0}}",
        "border.focused": "{{ACCENT}}",
        "border.selected": "{{ACCENT}}",
        "border.transparent": "#00000000",
        "border.disabled": "{{ZED_SURFACE0}}",
        "elevated_surface.background": "{{ZED_SURFACE1}}",
        "surface.background": "{{ZED_SURFACE0}}",
        "background": "{{WINDOW_BG}}",
        "element.background": "{{ZED_SURFACE0}}",
        "element.hover": "{{ZED_SURFACE1}}",
        "element.active": "{{ZED_SURFACE2}}",
        "element.selected": "{{ZED_SURFACE2}}",
        "element.disabled": "{{ZED_SURFACE0}}",
        "drop_target.background": "{{ZED_SURFACE2}}80",
        "ghost_element.background": "#00000000",
        "ghost_element.hover": "{{ZED_SURFACE0}}",
        "ghost_element.active": "{{ZED_SURFACE1}}",
        "ghost_element.selected": "{{ZED_SURFACE1}}",
        "ghost_element.disabled": "#00000000",
        "text": "{{VIEW_FG}}",
        "text.muted": "{{ZED_SUBTEXT0}}",
        "text.placeholder": "{{ZED_SUBTEXT1}}",
        "text.disabled": "{{ZED_SUBTEXT1}}",
        "text.accent": "{{ACCENT}}",
        "icon": "{{VIEW_FG}}",
        "icon.muted": "{{ZED_SUBTEXT0}}",
        "icon.disabled": "{{ZED_SUBTEXT1}}",
        "icon.placeholder": "{{ZED_SUBTEXT1}}",
        "icon.accent": "{{ACCENT}}",
        "status_bar.background": "{{ZED_CRUST}}",
        "title_bar.background": "{{ZED_CRUST}}",
        "title_bar.inactive_background": "{{WINDOW_BG}}",
        "toolbar.background": "{{ZED_SURFACE0}}",
        "tab_bar.background": "{{ZED_CRUST}}",
        "tab.inactive_background": "{{WINDOW_BG}}",
        "tab.active_background": "{{VIEW_BG}}",
        "editor.foreground": "{{VIEW_FG}}",
        "editor.background": "{{VIEW_BG}}",
        "editor.gutter.background": "{{VIEW_BG}}",
        "editor.subheader.background": "{{ZED_SURFACE0}}",
        "editor.active_line.background": "{{ZED_SURFACE0}}40",
        "editor.highlighted_line.background": "{{ZED_SURFACE0}}",
        "editor.line_number": "{{ZED_OVERLAY0}}",
        "editor.active_line_number": "{{VIEW_FG}}",
        "editor.hover_line_number": "{{ZED_SUBTEXT0}}",
        "editor.invisible": "{{ZED_OVERLAY0}}",
        "editor.wrap_guide": "{{ZED_OVERLAY0}}20",
        "editor.active_wrap_guide": "{{ZED_OVERLAY0}}40",
        "terminal.background": "{{VIEW_BG}}",
        "terminal.foreground": "{{VIEW_FG}}",
        "terminal.bright_foreground": "{{ANSI_WHITE_BRIGHT}}",
        "terminal.dim_foreground": "{{ZED_SUBTEXT0}}",
        "terminal.ansi.black": "{{ANSI_BLACK}}",
        "terminal.ansi.bright_black": "{{ANSI_BLACK_BRIGHT}}",
        "terminal.ansi.red": "{{ANSI_RED}}",
        "terminal.ansi.bright_red": "{{ANSI_RED_BRIGHT}}",
        "terminal.ansi.green": "{{ANSI_GREEN}}",
        "terminal.ansi.bright_green": "{{ANSI_GREEN_BRIGHT}}",
        "terminal.ansi.yellow": "{{ANSI_YELLOW}}",
        "terminal.ansi.bright_yellow": "{{ANSI_YELLOW_BRIGHT}}",
        "terminal.ansi.blue": "{{ANSI_BLUE}}",
        "terminal.ansi.bright_blue": "{{ANSI_BLUE_BRIGHT}}",
        "terminal.ansi.magenta": "{{ANSI_MAGENTA}}",
        "terminal.ansi.bright_magenta": "{{ANSI_MAGENTA_BRIGHT}}",
        "terminal.ansi.cyan": "{{ANSI_CYAN}}",
        "terminal.ansi.bright_cyan": "{{ANSI_CYAN_BRIGHT}}",
        "terminal.ansi.white": "{{ANSI_WHITE}}",
        "terminal.ansi.bright_white": "{{ANSI_WHITE_BRIGHT}}",
        "link_text.hover": "{{ANSI_BLUE}}",
        "version_control.added": "{{ANSI_GREEN}}",
        "version_control.modified": "{{ANSI_YELLOW}}",
        "version_control.deleted": "{{ANSI_RED}}",
        "conflict": "{{ANSI_YELLOW}}",
        "conflict.background": "{{ANSI_YELLOW}}20",
        "conflict.border": "{{ANSI_YELLOW}}80",
        "created": "{{ANSI_GREEN}}",
        "created.background": "{{ANSI_GREEN}}20",
        "created.border": "{{ANSI_GREEN}}80",
        "deleted": "{{ANSI_RED}}",
        "deleted.background": "{{ANSI_RED}}20",
        "deleted.border": "{{ANSI_RED}}80",
        "error": "{{ANSI_RED}}",
        "error.background": "{{ANSI_RED}}20",
        "error.border": "{{ANSI_RED}}80",
        "hint": "{{ANSI_BLUE}}",
        "hint.background": "{{ANSI_BLUE}}20",
        "hint.border": "{{ANSI_BLUE}}80",
        "info": "{{ANSI_BLUE}}",
        "info.background": "{{ANSI_BLUE}}20",
        "info.border": "{{ANSI_BLUE}}80",
        "modified": "{{ANSI_YELLOW}}",
        "modified.background": "{{ANSI_YELLOW}}20",
        "modified.border": "{{ANSI_YELLOW}}80",
        "success": "{{ANSI_GREEN}}",
        "success.background": "{{ANSI_GREEN}}20",
        "success.border": "{{ANSI_GREEN}}80",
        "warning": "{{ANSI_YELLOW}}",
        "warning.background": "{{ANSI_YELLOW}}20",
        "warning.border": "{{ANSI_YELLOW}}80",
        "syntax": {
          "attribute":   {"color": "{{ANSI_BLUE}}",    "font_style": null, "font_weight": null},
          "boolean":     {"color": "{{ANSI_YELLOW}}",  "font_style": null, "font_weight": null},
          "comment":     {"color": "{{ZED_OVERLAY0}}", "font_style": null, "font_weight": null},
          "constant":    {"color": "{{ANSI_YELLOW}}",  "font_style": null, "font_weight": null},
          "constructor": {"color": "{{ANSI_BLUE}}",    "font_style": null, "font_weight": null},
          "enum":        {"color": "{{ANSI_CYAN}}",    "font_style": null, "font_weight": null},
          "function":    {"color": "{{ANSI_BLUE}}",    "font_style": null, "font_weight": null},
          "keyword":     {"color": "{{ANSI_MAGENTA}}", "font_style": null, "font_weight": null},
          "number":      {"color": "{{ANSI_YELLOW}}",  "font_style": null, "font_weight": null},
          "operator":    {"color": "{{ANSI_CYAN}}",    "font_style": null, "font_weight": null},
          "property":    {"color": "{{ANSI_RED}}",     "font_style": null, "font_weight": null},
          "string":      {"color": "{{ANSI_GREEN}}",   "font_style": null, "font_weight": null},
          "type":        {"color": "{{ANSI_CYAN}}",    "font_style": null, "font_weight": null},
          "variable":    {"color": "{{VIEW_FG}}",      "font_style": null, "font_weight": null}
        }
      }
    },
    {
      "name": "Plasma Master Dark",
      "appearance": "dark",
      "style": {
        "border": "{{ZED_SURFACE1}}",
        "border.variant": "{{ZED_SURFACE0}}",
        "border.focused": "{{ACCENT}}",
        "border.selected": "{{ACCENT}}",
        "border.transparent": "#00000000",
        "border.disabled": "{{ZED_SURFACE0}}",
        "elevated_surface.background": "{{ZED_SURFACE1}}",
        "surface.background": "{{ZED_SURFACE0}}",
        "background": "{{WINDOW_BG}}",
        "element.background": "{{ZED_SURFACE0}}",
        "element.hover": "{{ZED_SURFACE1}}",
        "element.active": "{{ZED_SURFACE2}}",
        "element.selected": "{{ZED_SURFACE2}}",
        "element.disabled": "{{ZED_SURFACE0}}",
        "drop_target.background": "{{ZED_SURFACE2}}80",
        "ghost_element.background": "#00000000",
        "ghost_element.hover": "{{ZED_SURFACE0}}",
        "ghost_element.active": "{{ZED_SURFACE1}}",
        "ghost_element.selected": "{{ZED_SURFACE1}}",
        "ghost_element.disabled": "#00000000",
        "text": "{{VIEW_FG}}",
        "text.muted": "{{ZED_SUBTEXT0}}",
        "text.placeholder": "{{ZED_SUBTEXT1}}",
        "text.disabled": "{{ZED_SUBTEXT1}}",
        "text.accent": "{{ACCENT}}",
        "icon": "{{VIEW_FG}}",
        "icon.muted": "{{ZED_SUBTEXT0}}",
        "icon.disabled": "{{ZED_SUBTEXT1}}",
        "icon.placeholder": "{{ZED_SUBTEXT1}}",
        "icon.accent": "{{ACCENT}}",
        "status_bar.background": "{{ZED_CRUST}}",
        "title_bar.background": "{{ZED_CRUST}}",
        "title_bar.inactive_background": "{{WINDOW_BG}}",
        "toolbar.background": "{{ZED_SURFACE0}}",
        "tab_bar.background": "{{ZED_CRUST}}",
        "tab.inactive_background": "{{WINDOW_BG}}",
        "tab.active_background": "{{VIEW_BG}}",
        "editor.foreground": "{{VIEW_FG}}",
        "editor.background": "{{VIEW_BG}}",
        "editor.gutter.background": "{{VIEW_BG}}",
        "editor.subheader.background": "{{ZED_SURFACE0}}",
        "editor.active_line.background": "{{ZED_SURFACE0}}40",
        "editor.highlighted_line.background": "{{ZED_SURFACE0}}",
        "editor.line_number": "{{ZED_OVERLAY0}}",
        "editor.active_line_number": "{{VIEW_FG}}",
        "editor.hover_line_number": "{{ZED_SUBTEXT0}}",
        "editor.invisible": "{{ZED_OVERLAY0}}",
        "editor.wrap_guide": "{{ZED_OVERLAY0}}20",
        "editor.active_wrap_guide": "{{ZED_OVERLAY0}}40",
        "terminal.background": "{{VIEW_BG}}",
        "terminal.foreground": "{{VIEW_FG}}",
        "terminal.bright_foreground": "{{ANSI_WHITE_BRIGHT}}",
        "terminal.dim_foreground": "{{ZED_SUBTEXT0}}",
        "terminal.ansi.black": "{{ANSI_BLACK}}",
        "terminal.ansi.bright_black": "{{ANSI_BLACK_BRIGHT}}",
        "terminal.ansi.red": "{{ANSI_RED}}",
        "terminal.ansi.bright_red": "{{ANSI_RED_BRIGHT}}",
        "terminal.ansi.green": "{{ANSI_GREEN}}",
        "terminal.ansi.bright_green": "{{ANSI_GREEN_BRIGHT}}",
        "terminal.ansi.yellow": "{{ANSI_YELLOW}}",
        "terminal.ansi.bright_yellow": "{{ANSI_YELLOW_BRIGHT}}",
        "terminal.ansi.blue": "{{ANSI_BLUE}}",
        "terminal.ansi.bright_blue": "{{ANSI_BLUE_BRIGHT}}",
        "terminal.ansi.magenta": "{{ANSI_MAGENTA}}",
        "terminal.ansi.bright_magenta": "{{ANSI_MAGENTA_BRIGHT}}",
        "terminal.ansi.cyan": "{{ANSI_CYAN}}",
        "terminal.ansi.bright_cyan": "{{ANSI_CYAN_BRIGHT}}",
        "terminal.ansi.white": "{{ANSI_WHITE}}",
        "terminal.ansi.bright_white": "{{ANSI_WHITE_BRIGHT}}",
        "link_text.hover": "{{ANSI_BLUE}}",
        "version_control.added": "{{ANSI_GREEN}}",
        "version_control.modified": "{{ANSI_YELLOW}}",
        "version_control.deleted": "{{ANSI_RED}}",
        "conflict": "{{ANSI_YELLOW}}",
        "conflict.background": "{{ANSI_YELLOW}}20",
        "conflict.border": "{{ANSI_YELLOW}}80",
        "created": "{{ANSI_GREEN}}",
        "created.background": "{{ANSI_GREEN}}20",
        "created.border": "{{ANSI_GREEN}}80",
        "deleted": "{{ANSI_RED}}",
        "deleted.background": "{{ANSI_RED}}20",
        "deleted.border": "{{ANSI_RED}}80",
        "error": "{{ANSI_RED}}",
        "error.background": "{{ANSI_RED}}20",
        "error.border": "{{ANSI_RED}}80",
        "hint": "{{ANSI_BLUE}}",
        "hint.background": "{{ANSI_BLUE}}20",
        "hint.border": "{{ANSI_BLUE}}80",
        "info": "{{ANSI_BLUE}}",
        "info.background": "{{ANSI_BLUE}}20",
        "info.border": "{{ANSI_BLUE}}80",
        "modified": "{{ANSI_YELLOW}}",
        "modified.background": "{{ANSI_YELLOW}}20",
        "modified.border": "{{ANSI_YELLOW}}80",
        "success": "{{ANSI_GREEN}}",
        "success.background": "{{ANSI_GREEN}}20",
        "success.border": "{{ANSI_GREEN}}80",
        "warning": "{{ANSI_YELLOW}}",
        "warning.background": "{{ANSI_YELLOW}}20",
        "warning.border": "{{ANSI_YELLOW}}80",
        "syntax": {
          "attribute":   {"color": "{{ANSI_BLUE}}",    "font_style": null, "font_weight": null},
          "boolean":     {"color": "{{ANSI_YELLOW}}",  "font_style": null, "font_weight": null},
          "comment":     {"color": "{{ZED_OVERLAY0}}", "font_style": null, "font_weight": null},
          "constant":    {"color": "{{ANSI_YELLOW}}",  "font_style": null, "font_weight": null},
          "constructor": {"color": "{{ANSI_BLUE}}",    "font_style": null, "font_weight": null},
          "enum":        {"color": "{{ANSI_CYAN}}",    "font_style": null, "font_weight": null},
          "function":    {"color": "{{ANSI_BLUE}}",    "font_style": null, "font_weight": null},
          "keyword":     {"color": "{{ANSI_MAGENTA}}", "font_style": null, "font_weight": null},
          "number":      {"color": "{{ANSI_YELLOW}}",  "font_style": null, "font_weight": null},
          "operator":    {"color": "{{ANSI_CYAN}}",    "font_style": null, "font_weight": null},
          "property":    {"color": "{{ANSI_RED}}",     "font_style": null, "font_weight": null},
          "string":      {"color": "{{ANSI_GREEN}}",   "font_style": null, "font_weight": null},
          "type":        {"color": "{{ANSI_CYAN}}",    "font_style": null, "font_weight": null},
          "variable":    {"color": "{{VIEW_FG}}",      "font_style": null, "font_weight": null}
        }
      }
    }
  ]
}
